name: DemisePlugin
main: com.thejounezz.demisegame.Game
version: 1.0
commands:
    demise:
      description: Gives a status of the game.
      usage: /<command>         
    joinDemise:
      description: Join the game.
      usage: /<command>
    leaveDemise:
      description: Leave the game.
      usage: /<command>
    startDemise:
      description: OP only, Sets the game state to "Running".
      usage: /<command>
    stopDemise:
      description: OP only, Sets the game state to "Not Running".
      usage: /<command>
    resetDemise:
      description: OP only, Resets the game.
      usage: /<command>
